defaults:
- repro_multiseq_base.yaml
- _self_
model_factory_ImplicitronModelFactory_args:
  model_GenericModel_args:
    chunk_size_grid: 16000
    view_pooler_enabled: false
    global_encoder_class_type: SequenceAutodecoder
    global_encoder_SequenceAutodecoder_args:
      autodecoder_args:
        n_instances: 20000
        encoding_dim: 256
