defaults:
- repro_multiseq_nerformer.yaml
- _self_
model_factory_ImplicitronModelFactory_args:
  model_GenericModel_args:
    view_pooler_args:
      feature_aggregator_class_type: AngleWeightedIdentityFeatureAggregator
